# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and deploy JAR app to Azure Web App - CalculeSimple

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Install project dependencies
        run: ./mvnw clean install -DskipTests

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'
      - name: Run code quality check
        run: |
              ./mvnw checkstyle:check
              ./mvnw spotbugs:check

      - name: Run tests
        run: ./mvnw test
               - name: Notify result
               if: always()
               uses: rtCamp/action-slack-notify@v2.1.3
               with:
                 status: ${{ job.status }}
                 fields: repo,message,author,commit
                 slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
                 slack_channel: ${{ secrets.SLACK_CHANNEL }}

      - name: Build & push Docker image
        with:
          image: ymeriaf5/springweb
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

